pattern_layout_mapping.objects.bulk_create([
    pattern_layout_mapping(
        payor="UHC",
        layout_id=5859,
        datatype="Claims",
        employergroup="Hattisar Ludo Club",
        layouttype="Tilde",
        pattern="718_UHC_941777_CLAIMS_[0-9]+_[0-9]+_SPLIT_941777medclm[0-9]+.TXT",
        addeddate=date(2024, 2, 8),
        modifieddate=date(2024, 3, 9),
    ),
    pattern_layout_mapping(
        payor="UHC",
        layout_id=5859,
        datatype="Claims",
        employergroup="Cinnamon Rolls",
        layouttype="Tilde",
        pattern="718_UHC_778989_CLAIMS_[0-9]+_[0-9]+_SPLIT_778989medclm[0-9]+.TXT",
        addeddate=date(2022, 2, 28),
        modifieddate=date(2024, 4, 21),
    ),
    pattern_layout_mapping(
        payor="UHC",
        layout_id=5859,
        datatype="Claims",
        employergroup="Momo Pasal",
        layouttype="Tilde",
        pattern="718_UHC_545678_CLAIMS_[0-9]+_[0-9]+_SPLIT_545678medclm[0-9]+.TXT",
        addeddate=date(2022, 8, 27),
        modifieddate=None,
    ),
    pattern_layout_mapping(
        payor="UHC",
        layout_id=5859,
        datatype="Claims",
        employergroup="Yasuda",
        layouttype="Tilde",
        pattern="718_UHC_525252_CLAIMS_[0-9]+_[0-9]+_SPLIT_525252medclm[0-9]+.TXT",
        addeddate=date(2026, 8, 16),
        modifieddate=None,
    ),
    pattern_layout_mapping(
        payor="UHC",
        layout_id=5859,
        datatype="Claims",
        employergroup="Home Glory",
        layouttype="Tilde",
        pattern="718_UHC_865787_CLAIMS_[0-9]+_[0-9]+_SPLIT_865787medclm[0-9]+.TXT",
        addeddate=date(2026, 10, 11),
        modifieddate=None,
    ),
    pattern_layout_mapping(
        payor="UHC",
        layout_id=6274,
        datatype="Claims",
        employergroup="Wool House",
        layouttype="Tilde",
        pattern="718_UHC_555444_CLAIMS_[0-9]+_[0-9]+_SPLIT_PEAKTECHNOLOGIES_[0-9]+_[0-9]+_[0-9]+_[0-9]+.TXT",
        addeddate=date(2026, 5, 6),
        modifieddate=None,
    ),
    pattern_layout_mapping(
        payor="UHC",
        layout_id=6649,
        datatype="Claims",
        employergroup="Chiya Cup",
        layouttype="Tilde",
        pattern="718_UHC_786754_CLAIMS_[0-9]+_[0-9]+_SPLIT_PEAKTECHNOLOGIES_ELIG_CLM_[0-9]+_[0-9]+_[0-9]+_[0-9]+.TXT",
        addeddate=date(2025, 11, 6),
        modifieddate=None,
    ),
])