# Generated by Django 6.0.3 on 2026-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterndashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('client', models.CharField(max_length=100)),
                ('egex', models.CharField(max_length=500)),
            ],
        ),
    ]
