# Generated by Django 6.0.3 on 2026-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterndashboard', '0002_tablelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablelog',
            old_name='egex',
            new_name='regex',
        ),
    ]
