# Generated by Django 6.0.3 on 2026-04-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterndashboard', '0003_rename_egex_tablelog_regex'),
    ]

    operations = [
        migrations.CreateModel(
            name='generated_patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('client', models.CharField(max_length=100)),
                ('regex', models.CharField(max_length=500)),
            ],
        ),
    ]
