# Generated by Django 6.0.3 on 2026-04-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterndashboard', '0004_generated_patterns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_patterns',
            name='filename',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='tablelog',
            name='filename',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
