# Generated by Django 6.0.3 on 2026-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterndashboard', '0005_alter_generated_patterns_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternLayoutMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payor', models.CharField(max_length=100)),
                ('layout_id', models.IntegerField()),
                ('datatype', models.CharField(max_length=100)),
                ('employergroup', models.CharField(max_length=100)),
                ('layouttype', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=500)),
                ('addeddate', models.DateField()),
                ('modifieddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='testdb',
        ),
    ]
