# Generated by Django 6.0.3 on 2026-04-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterndashboard', '0006_patternlayoutmapping_delete_testdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatternLayoutMapping',
            new_name='pattern_layout_mapping',
        ),
    ]
